### ISSUE TITLE
Getting "exponent is larger than modulus" error when tried with Windows 10 Pin

### ISSUE THREAD

**Issue by rajapudikishore** [xarenard/webauthn_fido_java_react#13]
Got below error using Windows Pin. Can you please let me know the resolution for this error

2021-07-21 06:31:12.020 ERROR 19452 --- [nio-8080-exec-5] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.orquanet.webauthn.crypto.cose.exception.CoseException: java.security.spec.InvalidKeySpecException: java.security.InvalidKeyException: exponent is larger than modulus] with root cause

java.security.InvalidKeyException: exponent is larger than modulus
	at java.base/sun.security.rsa.RSAPublicKeyImpl.checkExponentRange(RSAPublicKeyImpl.java:151) ~[na:na]
	at java.base/sun.security.rsa.RSAPublicKeyImpl.<init>(RSAPublicKeyImpl.java:95) ~[na:na]
	at java.base/sun.security.rsa.RSAKeyFactory.generatePublic(RSAKeyFactory.java:339) ~[na:na]
	at java.base/sun.security.rsa.RSAKeyFactory.engineGeneratePublic(RSAKeyFactory.java:234) ~[na:na]
	at java.base/java.security.KeyFactory.generatePublic(KeyFactory.java:352) ~[na:na]
	at org.orquanet.webauthn.crypto.cose.mapper.CoseMapper.rsaPublicKey(CoseMapper.java:118) ~[classes/:na]
	at org.orquanet.webauthn.crypto.cose.mapper.CoseMapper.keyInfo(CoseMapper.java:103) ~[classes/:na]
	at org.orquanet.webauthn.webauthn.attestation.validation.attestation.packed.self.PackedDerogateAttestationValidator.verify(PackedDerogateAttestationValidator.java:35) ~[classes/:na]
	at org.orquanet.webauthn.webauthn.attestation.validation.attestation.AttestationValidator.verify(AttestationValidator.java:48) ~[classes/:na]
	at org.orquanet.webauthn.webauthn.attestation.validation.AuthenticatorAttestationValidator.validate(AuthenticatorAttestationValidator.java:14) ~[classes/:na]
	at org.orquanet.webauthn.controller.fido.FidoRegistrationController.registerFinal(FidoRegistrationController.java:148) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]

**Comment by xarenard** [comment]
hi

Which jdk version are you using?
